### ISSUE TITLE
Any alternative for like express "res.download(...)"  for sending files?

### ISSUE THREAD

**Issue by devalexqt** [aaronwlee/Attain#11]
Express have res.download(..) method https://expressjs.com/ru/api.html#res.download to handle file  downloading for user  action in browser, is it any alternative here?

**Comment by aaronwlee** [comment]
https://github.com/aaronwlee/Attain#response
I've updated download() and sendFile() at v0.5 
please make sure to reload the module and read the documentation.

**Comment by devalexqt** [comment]
Nice!

**Comment by devalexqt** [comment]
Please remove `console.log` from `res.download()` function.

**Comment by devalexqt** [comment]
Is it read file to RAM and then send to client? If so, then it's bad for big files to download and we need stream based downloader.

**Comment by aaronwlee** [comment]
I tested with 2GB file transfer through the web browser and It spent nothing. However, this test is not accurate due to the fact that I only keep on eyes on the deno.exe process. 

I couldn't find the best way to test memory usage. Deno does not have a process.memoryUsage method yet.

If you found this kind of issue, then please let me know
Thank you a lot :)
